build:
  number: 1
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

about:
    home: http://www.cs.cmu.edu/~ckingsf/software/sailfish/
    license: GPLv3
    summary: Rapid Mapping-based Isoform Quantification from RNA-Seq Reads

package:
    name: sailfish
    version: 0.7.6

source:
    fn: v0.7.6.tar.gz
    url: https://github.com/kingsfordgroup/sailfish/archive/v0.7.6.tar.gz
    md5: ae8d935a27a7194cd33682ff4f6722a7

requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - cmake
    - tbb
    - autoconf
  run:
    - boost {{CONDA_BOOST}}*
    - tbb

test:
    commands:
      - sailfish --help
