package:
  name: stack
  version: '1.1.2'

source:
  fn: stack-1.1.2-linux-x86_64.tar.gz
  url: https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz

build:
  number: 0
  skip: 

test:
  commands:
    - stack --help

about:
  home: www.haskellstack.org/
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
